server:
  port: 8088
spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://81.69.15.253:3306/foodie-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true

    password: 123321